### ISSUE TITLE
No module named 'phonenumber_field' Getting error

### ISSUE THREAD

**Issue by deeprajsinha** [CuriousLearner/django-phone-verify#1]
hi ,
i want to used your package and i installed it go through the documentation but while running server i m getting error ... 
from phonenumber_field.modelfields import PhoneNumberField
ModuleNotFoundError: No module named 'phonenumber_field'

not able to use your package.

**Comment by CuriousLearner** [comment]
Do you have the code available publically?

Can you mention exact steps to replicate this issue?

**Comment by CuriousLearner** [comment]
Hi @deeprajsinha 

Thanks for your report. We've fixed the issue & created a new release on pypi. You can install a new version of the package from pypi by running the following command:

`pip install django-phone-verify==0.1.1`

Thanks again!

**Comment by Griffins-sys254** [comment]
Hello I am getting the same error and I have followed the above steps to handle it and it does not seem to work... how do I go about this?

**Comment by lmrsantos** [comment]
I was facing the same issue and decided to try it with terminal in bash mode instead. It worked!
