### ISSUE TITLE
An example app  for demonstration

### ISSUE THREAD

**Issue by jayantamadhav** [CuriousLearner/django-phone-verify#14]
Although the docs are really helpful, an example app the demonstrate the usage would be really helpful.

**Comment by CuriousLearner** [comment]
Hi @jayantamadhav !

We've recently added usage docs, which describes how to integrate this with your app including routing and overriding endpoints to accomplish your use case.

Have you checked out these: https://github.com/CuriousLearner/django-phone-verify/blob/master/docs/usage.rst ?

**Comment by jayantamadhav** [comment]
Since you wrote this module, it'll be easy for you to point to docs, but for someone new , somethings wont make sense
like for example in your api_endpoints docs
'POST /api/phone/register'
post request from where?  which view?

**Comment by CuriousLearner** [comment]
The docs for endpoints and usage are linked from the README.

For the example you took, the API is an interface and if someone is using this package, a basic knowledge about understanding HTTP methods and endpoint is expected.

How to make your app is already described in [usage.rst](https://github.com/CuriousLearner/django-phone-verify/blob/master/docs/usage.rst) docs. If not, then what are you exactly suggesting? 

The initial usage you opened this issue for is already described.

**Comment by jayantamadhav** [comment]
Yes, thank you very much

**Comment by CuriousLearner** [comment]
Thanks for your contribution!

I hope that would help you. I'm closing this issue now.

Thanks again!
