### ISSUE TITLE
Add feature of one-time-password to restrict using a single code only once

### ISSUE THREAD

**Issue by CuriousLearner** [CuriousLearner/django-phone-verify#3]
Currently, a code can be used multiple times for auth. The goal is to restrict it's usage to one-time-password if needed by users.

**Comment by storymode7** [comment]
I think this issue can be closed now. It's dealt with in: https://github.com/CuriousLearner/django-phone-verify/commit/8c67aa6b45b55eaedeeaa1e73ef3a94455ef0701

**Comment by CuriousLearner** [comment]
Sure! Thanks!
