### ISSUE TITLE
fields

### ISSUE THREAD

**Issue by samson1998** [CuriousLearner/django-phone-verify#33]
What should be added to sandbox token and secret field in the settings.py file?

**Comment by CuriousLearner** [comment]
The `sandbox_token` is only applicable in case you want to use a sandbox backend (https://github.com/CuriousLearner/django-phone-verify/blob/master/phone_verify/backends/twilio.py#L32) and not an actual backend (https://github.com/CuriousLearner/django-phone-verify/blob/master/phone_verify/backends/twilio.py#L12).

I don't get which secret field are you referring to in settings.py file. Can you please elaborate that?

**Comment by samson1998** [comment]
PHONE_VERIFICATION = {
    'BACKEND': 'phone_verify.backends.twilio.TwilioBackend',
    'OPTIONS': {
        'SID': '############################
        'SECRET': I mean this field,
        'FROM': '+12016361235',
        'SANDBOX_TOKEN':#######################,
    },
    'TOKEN_LENGTH': 6,
    'MESSAGE': 'Welcome to {app}! Please use security code {security_code} to proceed.',
    'APP_NAME': 'Phone Verify',
    'SECURITY_CODE_EXPIRATION_TIME': 3600,  # In seconds only
    'VERIFY_SECURITY_CODE_ONLY_ONCE': True,  # If False, then a security code can be used multiple times for verification
}

**Comment by CuriousLearner** [comment]
That is the secret that you get from Twilio along with your SID.
