### ISSUE TITLE
catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by charanjit-singh** [CuriousLearner/django-phone-verify#41]
Why?

**Comment by CuriousLearner** [comment]
Can you please elaborate on what you're asking here? Giving just a title is not apt.

**Comment by CuriousLearner** [comment]
@charanjit-singh Can you please elaborate your question?

**Comment by CuriousLearner** [comment]
This issue does not have enough information or context and the OP hasn't replied from months. I'm closing it now.

If you want to elaborate on this question/concern, please reopen this issue.
