### ISSUE TITLE
Failing on  BaseBacked.generate_session_token()

### ISSUE THREAD

**Issue by lfx** [CuriousLearner/django-phone-verify#51]
Hello, 

I think I found bug here:
https://github.com/CuriousLearner/django-phone-verify/blob/eb1c970981a91dbf6f550560e4daf586e699b3e3/phone_verify/backends/base.py#L52

`jwt.encode(data, django_settings.SECRET_KEY)` [returns string](https://pyjwt.readthedocs.io/en/stable/api.html#module-jwt), so `decode()` method is not found, therefore call fails.

Tested on python 3.8.5 and 3.8.6.

Btw, super useful lib, thank you for creating! 👍

**Comment by sabuj7177** [comment]
I also faced a similar problem. This resolves when ".decode()" is removed from base.py file. Any solution or update?

**Comment by CuriousLearner** [comment]
I would look into this soon-ish and also welcome others to add a pull request.

Thanks!

**Comment by m7salam** [comment]
@CuriousLearner I have provided a pull request here https://github.com/CuriousLearner/django-phone-verify/pull/53 to solve this problem 

it solved it for me and working now

hopefully you can merge it soon

have a great day and thanks for the great library

**Comment by vhawk19** [comment]
@CuriousLearner  Would #53 be merged soon?

**Comment by CuriousLearner** [comment]
Depends on when is it ready with a fix.

**Comment by Tobeyforce** [comment]
I also have this bug with python 3.9.1

**Comment by Tobeyforce** [comment]
@CuriousLearner Status on this? 
Python 3.8.5, 3.9.1 still not working. Would love to see compatability fixed :)
Crossing my fingers.

**Comment by CuriousLearner** [comment]
Shall be fixed in #58

**Comment by CuriousLearner** [comment]
Released django-phone-verify v2.0.1 (https://pypi.org/project/django-phone-verify/2.0.1/) and it has it fixed.

We now support Py{36,37,38,39} with Django{20,21,22,30,31}.

Thank you everyone (@lfx @m7salam @vhawk19 @sabuj7177 @Tobeyforce @belal-bh ) for their inputs!
