### ISSUE TITLE
Error in sending verification code to phone number

### ISSUE THREAD

**Issue by Hophoet** [CuriousLearner/django-phone-verify#52]
Hello, 

I get this twilio erorr during the /phone/register (with phone_number)

![phone_auth_error](https://user-images.githubusercontent.com/52464453/104818962-a547a380-5822-11eb-9ae1-72ede5bac6c7.png)

Testing on  Python 3.9

Thank you for this lib, very great!!!

**Comment by CuriousLearner** [comment]
Hi @Hophoet !

It seems you haven't set the actual keys from your twilio account in the settings of your project. Please have a look here: https://github.com/CuriousLearner/django-phone-verify/blob/master/docs/usage.rst#configuration

Let me know if this issue persists.

**Comment by Hophoet** [comment]
> Hi @Hophoet !
> 
> It seems you haven't set the actual keys from your twilio account in the settings of your project. Please have a look here: https://github.com/CuriousLearner/django-phone-verify/blob/master/docs/usage.rst#configuration
> 
> Let me know if this issue persists.

thank bro, it work
