### ISSUE TITLE
RemovedInDjango41Warning: 'phone_verify' defines default_app_config = 'phone_verify.apps.PhoneVerificationConfig'

### ISSUE THREAD

**Issue by mnrudkovskyi** [CuriousLearner/django-phone-verify#90]
#91 
``RemovedInDjango41Warning: 'phone_verify' defines default_app_config = 'phone_verify.apps.PhoneVerificationConfig'. Django now detects this configuration automatically. You can remove default_app_config.

More about this https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery

**fix** for phone_verify/__init__.py
```
import django


if django.VERSION < (3, 2):
    default_app_config = "phone_verify.apps.PhoneVerificationConfig"
```

**Comment by CuriousLearner** [comment]
Fixed in #91
